#cloud-config
package_update: true
package_upgrade: true

packages:
  - build-essential
  - dkms
  - linux-headers-$(uname -r)
  - ubuntu-drivers-common

runcmd:
  - ubuntu-drivers autoinstall
  - reboot

